### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by CamilV** [CamilV/OdometryTask#3]
- [ ]  6 mm hole for the switch
- [ ]  5 mm hole for the LED
- [ ]  M&M dropping mechanism
- [ ]  final assembly
- [ ]  wire connector MD25 - Arduino Shield
